dist: trusty
sudo: required

# temp disable cache
cache:
  directories:
   - $HOME/mc
   - $HOME/.cache/bazel

before_cache:
  - rm -f bazel-*
  - rm -rf $HOME/.cache/bazel/_bazel_travis/install

compiler:
  - gcc
  - clang

language:
  - java
  - c++
  - python

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

# JDK configuration, ref: https://github.com/travis-ci/travis-ci/issues/2316
matrix:
  include:
    - os: linux
      jdk: oraclejdk8  # Building Bazel requires JDK8.
      # Bazel does not support jdk 9 yet
      env:
        - CACHE_NAME=linux
    # - os: osx
    #   osx_image: xcode8.3  # Building Bazel requires JDK8.
    #   env:
    #     - CACHE_NAME=osx


before_install:
  # debug
  - . .travis/before_install.sh
  - pwd # check current dir, result: /home/travis/build/yuikns/argcv
  - echo $PATH
  - df -h
  - date
  - uname -a
  # - python -v

install:
  - . .travis/install.sh
  - echo $PATH
  # setup python
  - ./setup
  - bazel fetch //...

script:
  # build by stage for cache
  - bazel build //examples/cxx/grpc/...
  - bazel build //examples/cxx:hello_world
  # - bazel build //...
  # - bazel test --genrule_strategy=standalone --spawn_strategy=standalone  //...
  - bazel test  //...
