language:
  - java
  - c++
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
before_install:
  - wget https://github.com/bazelbuild/bazel/archive/0.4.5.zip  # Replace with desired version
  - unzip 0.4.5.zip
  - cd bazel-0.4.5
  - ./compile.sh
  - sudo cp output/bazel /usr/bin/bazel
  - cd ..
  - rm -rf bazel-0.4.5
script:
  - bazel build //...
  - bazel test //...
