cc_binary(
    name = "hello_curl",
    srcs = [
          "hello_curl.cc",
    ],
    deps = [
        "//external:glog",
        "//external:curl",
    ],
    visibility = ["//visibility:public"],
)
